name: Feature Request
description: Add a new feature
title: "[Feature] "
labels:
  - feature

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should be added?

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed?

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines completion?